spring:
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  #   url: jdbc:h2:file:./db/V1_0__init
  h2:
    console:
      path: /h2
      settings:
        trace: false
        web-allow-others: false
      enabled: true
  profiles:
    active: application
logging:
  level:
    com.wxs.mybatisplus: debug
server:
  port: 9000